### ISSUE TITLE
Cron is broken...again

### ISSUE THREAD

**Issue by philcryer** [philcryer/lipsync#10]
cron is not working as advertised, and that's the part that actually pulls changes from the server, so without it, lipsync only appears to be doing syncs in one direction. I need to read up on how to have a setup script create a cron script, I copied an existing one in /etc/cron.d, but it fails...however, if I run this command (as root) all is good, updates on the server come down to the client:

`su phil -c "/usr/local/bin/lipsync"`

of course the above won't work for you unless your (user)name is also phil :)

**Comment by philcryer** [comment]
Ok, Cron is fixed via this commit: https://github.com/philcryer/lipsync/commit/8c3be966d4aa770fcb35697ac29c89e72b6693f3

I had root trying to setup a crontab for itself, but now the install just adds a line to the user's crontab - much better, more secure, best practices, etc...done!

**Comment by bacardi55** [comment]
It is indeed a much cleaner / safer way to do it :)
I don't like to use root when I can avoid it
