### ISSUE TITLE
cat: /home/phil/.lipsyncd/lipsyncd.log: No such file or directory

### ISSUE THREAD

**Issue by tristan-k** [philcryer/lipsync#11]
I recently installed lipsync on my plug computer but I dont think it it's working properly. Changes made to the client arent synced back to the server but changes made to the server are synced to the client. Also I do have to run lipsync manually and then I get "cat: /home/phil/.lipsyncd/lipsyncd.log: No such file or directory". Where is the config files stored?

**Comment by philcryer** [comment]
> run lipsync manually and then I get "cat: /home/phil/.lipsyncd/lipsyncd.log: No such file or directory". 
> Where is the config files stored?

I still had a path hardcoded from some testing last week, I've fixed this, here's the commit:
https://github.com/philcryer/lipsync/commit/be3557b32acd74f9842decdd5224bface6737493

**Comment by philcryer** [comment]
> Changes made to the client arent synced back to the server but changes made to the server are synced to the client

Currently lsyncd watches on the client and syncs to the server - but changes on the server have to have a different rsync command run, this is currently handled by cron - but I broke the cron functionality last week, it's the top of my list to fix today. Here's the issue https://github.com/philcryer/lipsync/issues/10

I'm closing this and will update that one when it's fixed - thank you for reporting these, and let me know if you need help after you get the new bin/lipsync file installed to /usr/local/bin

**Comment by philcryer** [comment]
...and as a followup, to sync changes from the server back to the link, run the following, as root:

su phil -c "/usr/local/bin/lipsync"

**Comment by philcryer** [comment]
Ha, and it was me writing that last comment where I said "...as root:" that I thought, that's not right...looked online, saw how you can add to a user's crontab from the command-line, so that's what the install script now does - much better, plus cron is now fixed. Thanks again
