### ISSUE TITLE
client syncing

### ISSUE THREAD

**Issue by anemes** [philcryer/lipsync#20]
Hello, 

   just set up the server with two clients. I am experiencing the following issues on both clients:

Occasionally a new file added to the sync directory on a client will be deleted.
Updates to existing files on a client will not sync across to  the server
Deleting files will occasionally have them recreated from the server.

Any suggestions how to track it down. The logs simply state exactly what is occurring.

**Comment by chungyan5** [comment]
hi 

please take a look my comment on Issue #18 and have a try

**Comment by philcryer** [comment]
I'm setting up a test of this with fresh code, will report back. Have
you submitted this as an issue on github/lipsync?

thanks for the note.

P

On Thu, May 12, 2011 at 6:58 PM, anemes
reply@reply.github.com
wrote:

> Hello,
> 
>   just set up the server with two clients. I am experiencing the following issues on both clients:
> 
> Occasionally a new file added to the sync directory on a client will be deleted.
> Updates to existing files on a client will not sync across to  the server
> Deleting files will occasionally have them recreated from the server.
> 
> Any suggestions how to track it down. The logs simply state exactly what is occurring.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/philcryer/lipsync/issues/20

## 

http://philcryer.com

**Comment by philcryer** [comment]
from a few other issues I've implemented a check which stops cron if there is already a client -> server sync running. I _think_ this will fix this one as well. https://github.com/philcryer/lipsync/commit/b4fbf4092ec9ec0da31d61bdec1408400fd0aea7

If not please reopen and we'll dig further. Thanks!

**Comment by philcryer** [comment]
I'd like to add you to my professional network on LinkedIn.
- Phil

Phil Cryer
Technical infrastructure engineer at Center for Library & Informatics at Woods Hole Marine Biological Laboratory
Greater St. Louis Area

Confirm that you know Phil Cryer:
https://www.linkedin.com/e/x6pvii-gtkqzpy9-6v/isd/4504898819/7nCROdUu/?hs=false&tok=3TdVBWE9Xkf4Y1

## 

You are receiving Invitation to Connect emails. Click to unsubscribe:
http://www.linkedin.com/e/x6pvii-gtkqzpy9-6v/XF8GNeFw28AxGIxmeHOe3cCgvv7wxqsFAqdZNlvXhL7xcd4koCIe34HgpCT9ez4DahoY5fqOHGZR0p4-6pI6GMdljrhcU8Q_Hv_iVL/goo/reply%2Bi-892501-102f2c4e0a1d5ae0dee0e33fbd4173c6956aff83%40reply%2Egithub%2Ecom/20061/I1560656338_1/?hs=false&tok=2LQlt79-bkf4Y1

(c) 2011 LinkedIn Corporation. 2029 Stierlin Ct, Mountain View, CA 94043, USA.
