### ISSUE TITLE
libsyncd unrecognized option '-delay'

### ISSUE THREAD

**Issue by tdcrenshaw** [philcryer/lipsync#21]
When running the install script for lipsync, the script exits with the error message 

```
Starting lipsyncd daemon.../usr/local/bin/lipsyncd: unrecognized option '-delay'
            NOTICE: lipsyncd failed to start...
```

Trying to just run libsyncd with the --delay option presents me with a similar message and after running --help, it appears my version of lsync (1.26) doesn't support this option. 

When I run libsyncd with no options, it appears to run, but whenever I create a document on my client, it is deleted when the cron script runs. Documents created on the server still show up and my log files display nothing out of the ordinary.

**Comment by philcryer** [comment]
Ah, so you need to have lsyncd2 installed - can you uninstall 1 and
install 2? I need to make the install script more intelligent and tell
you if you only have 1 installed. Let me know if you need the steps,
shouldn't be too much trouble.

P

On Wed, May 18, 2011 at 12:01 AM, tdcrenshaw
reply@reply.github.com
wrote:

> When running the install script for lipsync, the script exits with the error message
> 
> ```
> Starting lipsyncd daemon.../usr/local/bin/lipsyncd: unrecognized option '-delay'
>                NOTICE: lipsyncd failed to start...
> ```
> 
> Trying to just run libsyncd with the --delay option presents me with a similar message and after running --help, it appears my version of lsync (1.26) doesn't support this option.
> 
> When I run libsyncd with no options, it appears to run, but whenever I create a document on my client, it is deleted when the cron script runs. Documents created on the server still show up and my log files display nothing out of the ordinary.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/philcryer/lipsync/issues/21

## 

http://philcryer.com

**Comment by tdcrenshaw** [comment]
I had already tried to build lsyncd 2.0.4, unfortunately it hangs while checking for the lua > 5.1.3 dependency. I have lua 5.1.4 installed using the package lua5.1 package. I'm assuming I need to adjust some sort of environmental variables so the config script knows where to find lua, but that sort of thing is a little over my head

**Comment by philcryer** [comment]
Often when you're building from source you need the -dev modules to
have the code headers - for lua in Debian I see: liblua5.1-0-dev You
could install that first, then try to recompile lsyncd2.x - otherwise
let me know what Linux version you're running, and the error message
and I can try to advise further.

Thanks

P

On Thu, May 19, 2011 at 5:42 PM, tdcrenshaw
reply@reply.github.com
wrote:

> I had already tried to build lsyncd 2.0.4, unfortunately it hangs while checking for the lua > 5.1.3 dependency. I have lua 5.1.4 installed using the package lua5.1 package. I'm assuming I need to adjust some sort of environmental variables so the config script knows where to find lua, but that sort of thing is a little over my head
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/philcryer/lipsync/issues/21#comment_1206923

## 

http://philcryer.com

**Comment by philcryer** [comment]
Closing this, the issue was with having lsyncd 1.x, and we only use 2.x now. If you couldn't install the required lua modules let me know, I had a list of them that I'll have to generate again, and then doc it.

**Comment by philcryer** [comment]
I'd like to add you to my professional network on LinkedIn.
- Phil

Phil Cryer
Technical infrastructure engineer at Center for Library & Informatics at Woods Hole Marine Biological Laboratory
Greater St. Louis Area

Confirm that you know Phil Cryer:
https://www.linkedin.com/e/-t4gbb2-gtkr00d4-b/isd/4504900039/UJRg1to9/?hs=false&tok=1h50H9tGHlf4Y1

## 

You are receiving Invitation to Connect emails. Click to unsubscribe:
http://www.linkedin.com/e/-t4gbb2-gtkr00d4-b/q_VPyIj8vwQia_lepDTU_aDbnZbix5BS_iU3QZjQ8ZbVc4DUD3ASy8i4kGBnesDA_W60H6KHLZBLc0NUsKUaK83_4FlE7xBG_mnuG3/goo/reply%2Bi-920068-62d62687fb16134dd9cf7207f6d1a342e2f9b4d2%40reply%2Egithub%2Ecom/20061/I1560656728_1/?hs=false&tok=0moPlZO1_lf4Y1

(c) 2011 LinkedIn Corporation. 2029 Stierlin Ct, Mountain View, CA 94043, USA.
