### ISSUE TITLE
Cannot sync large size of file

### ISSUE THREAD

**Issue by chungyan5** [philcryer/lipsync#22]
I copy a *.iso into client which size in around 700M, i find lipsync(/usr/local/bin/lipsyncd) try to copy from client to server. It takes time to copying. In the meanwhile, the client cron job for lipsync(/usr/local/bin/lipsync) is running, and detect server side does not contain this large file, then remove this large file in client. 

Manually solution, 
*disable client cron job for lipsync, and wait for a while to make sure it is really stopped. 
*create this large file
*wait for a while to let lipsync(/usr/local/bin/lipsyncd) try to copy from client to server
*make sure both size have same file
*re-enable client cron job for lipsync

I hope, we can have this automatic in future.

**Comment by chungyan5** [comment]
hi all

i separate the above issue in two: server to client and client to server. 

For "server to client"
I disable the lipsyncd daemon. Then create a large size of file in server. The user cron job in client will auto. start on each minute. Downloading from Server to client, and it create a hidden file like that .DSCN2041.AVI.nxy7Wk as intermediate file. 

The problem comes out as, the another minute is coming, then user cron job start. It finds the server does not have this .DSCN2041.AVI.nxy7Wk intermediate file, and want to remove it. Lastly, the large size of file is always cannot completely download. 

In the case of if the client to server daemon does not disable, it is more complication that this intermediate file will be transferred back to server, but the size of this intermediate files between client and server are always different because of downloading and transferring. I have not dug into this case further more. 

So i modify the /usr/local/bin/lipsync as following by adding a lock file as semaphore: 

<pre>
 ...
IFS=
err=0

###############
# adding a lock file as semaphore
###############
LOCk_FILE=/home/$USER_NAME/.lipsyncd/lipsync_lock
if [ -e $LOCk_FILE ]; then 
    exit $err
else
    touch $LOCk_FILE
fi

###############
# run the rsync command to check server for updated files
###############
...
            /usr/local/bin/lipsync-notify "$TOTAL_TRANS files synced"
        fi
fi

###############
# remove this semaphore before exit
###############
rm $LOCk_FILE

###############
# returns the exit code of rsync to lsyncd
###############
...
</pre>


It is only a quick solution, please suggest, if anyone has a another better solution.

**Comment by chungyan5** [comment]
For consideration of the case in both direction sync:

==Short form declaration:
S -- Server
C -- Client
C.tmp -- transferring temporary file and save in Client side, such as .DSCN2041.AVI.nxy7Wk

==Case in Server download to Client
*S down C.tmp and takes long time by transferring through network (S to C is locked; C to S is no affected)
*C.tmp to C takes long time by copying partition to partition (S to C is locked; C to S is affected and C sync back S, but S already has that file, it is alright)
*i find it corrupts the large size of file, and create a race conditions to let the file size greater and greater, not what i want to see in the above description

==Case in Client upload to Server
*C -> S.tmp and takes long time by transferring through network (S to C does not lock, S does not have that file, but C has that file, will remove C file)
- ... still under observation

It is what my observation so far and share, please give any comment

**Comment by ka2er** [comment]
I believe that if we do large transfer (ie that take time) from client to server, in the same time the cron could be fired.
If the cron is fired, it doesn't show the large file on server on try to delete on client side.... This result in a file loss...

this patch seems to correct issue for me :

diff --git a/bin/lipsync b/bin/lipsync
index 9a2c541..41ee2ca 100644
--- a/bin/lipsync
+++ b/bin/lipsync
@@ -10,6 +10,20 @@ if [ -e $CONF_FILE ]; then
         . $CONF_FILE
 fi

+LOG_FILE=/home/$USER_NAME/.lipsyncd/lipsyncd.log
+
+###############
+# prevent data loss if there is a running rsync launched by lsyncd
+###############
+
+echo "Counting RSYNC process" >> $LOG_FILE
+eval NB_RSYNC_PROCESS=`ps aux | grep rsync | grep -v rsyncssh | grep -cv grep` 
+echo "found $NB_RSYNC_PROCESS" >> $LOG_FILE
+if [ $NB_RSYNC_PROCESS -ne 0 ]; then
-       echo "Prevent cron $0 from running (another sync is already running)" >> $LOG_FILE
-       exit 0
  +fi
  +

**Comment by philcryer** [comment]
thanks for this, going to test it out now...

**Comment by philcryer** [comment]
Ok, I used code from ka2er's post above, and I think this solves the race condition issue. Commit is: https://github.com/philcryer/lipsync/commit/b4fbf4092ec9ec0da31d61bdec1408400fd0aea7 

I will check, this should also fix some other bugs - my testing looks good, if this still breaks for you feel free to reopen. Thanks!
