### ISSUE TITLE
Seems lipsyncd is removed from repo

### ISSUE THREAD

**Issue by kvz** [philcryer/lipsync#24]

**Comment by ka2er** [comment]
lipsyncd is just a link to lsyncd so you need to satisfy dependancy and then install.sh will create the link for you

**Comment by philcryer** [comment]
installer checks for lsyncd and dies if it's not found. when it is found it does a symlink from lipsyncd, I've tested this and it's working. Please reopen with more detail if this is still an issue - and thanks kvz for all your issues! You've helped a lot! Thanks!
