### ISSUE TITLE
sync seems to be just a unidirectional rsync

### ISSUE THREAD

**Issue by kvz** [philcryer/lipsync#27]

**Comment by philcryer** [comment]
Is this issue still valid? right now lsyncd kicks off sync if there are changes locally, meanwhile changes on the server are check via lipsync called via cron (two sep scripts) I've been able to setup a many (clients) to one (server) and it's working, perhaps this was an issue with the race condition solved with this commit? https://github.com/philcryer/lipsync/commit/b4fbf4092ec9ec0da31d61bdec1408400fd0aea7 

if this issue still occurs, feel free to reopen this with more detail. Thanks!

**Comment by Thynix** [comment]
I'm having this problem too. For some reason lipsyncd is not running and when the cronjob runs it just wipes everything I add.  The symptom I'm seeing is that the install script ends with
`NOTICE: lipsyncd is running as pid 
Check lipsyncd.log for details`
How can I help figure this out?

**Comment by Thynix** [comment]
This may be due to trying to use lipsync with multiple users.
