### ISSUE TITLE
rsync just runs every minute

### ISSUE THREAD

**Issue by kvz** [philcryer/lipsync#28]
There's no locking (or use of e.g. Tim Kay's solo). So if 1 rsync takes an hour, you'll get an overlap every minute, eventually crashing the server.

That's it, this project isn't ready for production at all, sorry.

**Comment by chungyan5** [comment]
i have 17G data to sync, rsync takes around 10minutes to monitor all 17G data and find which files should copy from server to client. Lsync sometimes cannot locate all updated files. So my harddisk is always very busy to be scanned for this 17G data. 

Any new solution to avoid this?

**Comment by philcryer** [comment]
working on this as part of another bug...will check for a running sync, and exit if there is one. will report back when it's fixed and link to the commit. thanks for the reports, it was stumping me for some time!

**Comment by philcryer** [comment]
these race condition issues should be fixed as part of: https://github.com/philcryer/lipsync/commit/b4fbf4092ec9ec0da31d61bdec1408400fd0aea7 

I will check, this should also fix some other bugs - my testing looks good, if this still breaks for you feel free to reopen. Thanks!
