### ISSUE TITLE
Use a lipsync-specific ssh-key

### ISSUE THREAD

**Issue by philcryer** [philcryer/lipsync#5]
goozbach asked:

> 1) Why not use a lipsync-specific ssh-key and corresponding ~/.ssh/
> config section?

Why not indeed, that's a great idea. Will look into it.

**Comment by goozbach** [comment]
I've got a good start doing this in my fork:

goozbach/lipsync@bff0f812bff05e0395bd2454fb53d760dc8c6ac4

## 

Derek aka goozbach

**Comment by philcryer** [comment]
Ah! very nice, I'll watch what you come up with and try it out when I have time.

**Comment by Dieterbe** [comment]
great idea???
that would only make things more complicated, without any benefit at all.

**Comment by philcryer** [comment]
if I ever relaunch lipsync in python or go...
